name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  version-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get Last Commit Message
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr '\n' ' ')  # Remove newlines
          echo "LAST_COMMIT_MESSAGE=$LAST_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Increment version
        if: ${{ !contains(env.LAST_COMMIT_MESSAGE, 'Increment version to') }}
        run: |
          VERSION_FILE="version.conf"
          if [ ! -f "$VERSION_FILE" ]; then
            echo 'VERSION="1.0.0.1"' > "$VERSION_FILE"
          else
            VERSION=$(grep -oP '(?<=VERSION=")[^"]+' "$VERSION_FILE")
            BASE_VERSION=$(echo "$VERSION" | cut -d. -f1-3)
            BUILD_NUMBER=$(echo "$VERSION" | cut -d. -f4)
            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
            NEW_VERSION="$BASE_VERSION.$NEW_BUILD_NUMBER"
            echo "VERSION=\"$NEW_VERSION\"" > "$VERSION_FILE"
          fi

      - name: Commit and Push Changes
        if: ${{ !contains(env.LAST_COMMIT_MESSAGE, 'Increment version to') }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.conf
          git commit -m "Increment version to $(grep -oP '(?<=VERSION=")[^"]+' version.conf)"
          git push
